export const bgColor = 'aliceblue';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_EMPLOYEES_SUCCESSFUL = 'FETCH_EMPLOYEES_SUCCESSFUL';
export const FETCH_EMPLOYEES_FAIL = 'FETCH_EMPLOYEES_FAIL';

export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESSFUL = 'FETCH_TASKS_SUCCESSFUL';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const FETCH_EVERYTHING = 'FETCH_EVERYTHING';
export const FETCH_EVERYTHING_SUCCESSFUL = 'FETCH_EVERYTHING_SUCCESSFUL';
export const FETCH_EVERYTHING_FAIL = 'FETCH_EVERYTHING_FAIL';

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
